#Lisko configuration
lisko:
  base_reg_role: USER

  jwt:
    secret: liskoksi
    ttl: 300


#Server configuration here
server:
  port: 2415

#Spring configuration
spring:
  datasource:
    url: jdbc:h2:file:./data/lisko;NON_KEYWORDS=user;INIT=RUNSCRIPT FROM './data/init.sql'
    driverClassName: org.h2.Driver
    username: lisko
    password: 1234
    initialization-mode: always

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console.enabled: true

  liquibase:
    default_schema: lisko
